/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import BusinessLogic.Drug;
import BusinessLogic.StoreDirectory;
import BusinessLogic.Supplier;
import BusinessLogic.SupplierDirectory;
import UserInterface.CvsAdmin.AdminWorkAreaJPanel;
import UserInterface.StoreAdmin.LoginJPanel;
import UserInterface.Supplier.SupplierLoginJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private SupplierDirectory supplierDirectory;
    private StoreDirectory storeDirectory;
    
    public MainJFrame() {
        initComponents();
        supplierDirectory = new SupplierDirectory();
        storeDirectory = new StoreDirectory();
        initializationFunction();
    }

    private void initializationFunction(){
        supplierDirectory = new SupplierDirectory();
        
        Supplier s1 = supplierDirectory.addSupplier();
        s1.setSupplierName("Supplier1");
        s1.setSupplierId(1);
        s1.setContact(1);
        for(int i=1; i<=5; i++){
            Drug d = s1.getDrugList().addDrug();
            d.setName("Drug1" + i);
            d.setId(10 + i);
            d.setLicenceNum("Licence1" + i);
            d.setConcentration("Concentration1" + i);
            d.setExpDate("Expiry1" + i);
            d.setManufacturer("Manufacturer1" + i);
            d.setMktdBy("Marketed By1" + i);
            d.setMfgContact(100 + i);
            d.setMfgAddress("Address1" + i);
            d.setPrice(10 * i);            
        }
               
        Supplier s2 = supplierDirectory.addSupplier();
        s2.setSupplierName("Supplier2");
        s2.setSupplierId(2);
        s2.setContact(2);
        for(int i=1; i<=5; i++){
            Drug d = s2.getDrugList().addDrug();
            d.setName("Drug2" + i);
            d.setId(20 + i);
            d.setLicenceNum("Licence2" + i);
            d.setConcentration("Concentration2" + i);
            d.setExpDate("Expiry2" + i);
            d.setManufacturer("Manufacturer2" + i);
            d.setMktdBy("Marketed By2" + i);
            d.setMfgContact(200 + i);
            d.setMfgAddress("Address2" + i);
            d.setPrice(20 * i);            
        }
        Supplier s3 = supplierDirectory.addSupplier();
        s3.setSupplierName("Supplier3");
        s3.setSupplierId(3);
        s3.setContact(3);
        for(int i=1; i<=5; i++){
            Drug d = s3.getDrugList().addDrug();
            d.setName("Drug3" + i);
            d.setId(30 + i);
            d.setLicenceNum("Licence3" + i);
            d.setConcentration("Concentration3" + i);
            d.setExpDate("Expiry3" + i);
            d.setManufacturer("Manufacturer3" + i);
            d.setMktdBy("Marketed By3" + i);
            d.setMfgContact(300 + i);
            d.setMfgAddress("Address3" + i);
            d.setPrice(30 * i);            
        }
        
        Supplier s4 = supplierDirectory.addSupplier();
        s4.setSupplierName("Supplier4");
        s4.setSupplierId(4);
        s4.setContact(4);
        for(int i=1; i<=5; i++){
            Drug d = s4.getDrugList().addDrug();
            d.setName("Drug4" + i);
            d.setId(40 + i);
            d.setLicenceNum("Licence4" + i);
            d.setConcentration("Concentration4" + i);
            d.setExpDate("Expiry4" + i);
            d.setManufacturer("Manufacturer4" + i);
            d.setMktdBy("Marketed By4" + i);
            d.setMfgContact(400 + i);
            d.setMfgAddress("Address4" + i);
            d.setPrice(40 * i);            
        }
        
        Supplier s5 = supplierDirectory.addSupplier();
        s5.setSupplierName("Supplier5");
        s5.setSupplierId(5);
        s5.setContact(5);
        for(int i=1; i<=5; i++){
            Drug d = s5.getDrugList().addDrug();
            d.setName("Drug5" + i);
            d.setId(50 + i);
            d.setLicenceNum("Licence5" + i);
            d.setConcentration("Concentration5" + i);
            d.setExpDate("Expiry5" + i);
            d.setManufacturer("Manufacturer5" + i);
            d.setMktdBy("Marketed By5" + i);
            d.setMfgContact(500 + i);
            d.setMfgAddress("Address5" + i);
            d.setPrice(50 * i);           
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userProcessContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cvsAdminBtn = new javax.swing.JButton();
        storeAdminBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        cvsAdminBtn.setText("CVS Admin");
        cvsAdminBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cvsAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvsAdminBtnActionPerformed(evt);
            }
        });

        storeAdminBtn.setText("Store Admin");
        storeAdminBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        storeAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeAdminBtnActionPerformed(evt);
            }
        });

        supplierBtn.setText("Supplier");
        supplierBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cvsAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(storeAdminBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(supplierBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(cvsAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(storeAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cvsAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvsAdminBtnActionPerformed
        AdminWorkAreaJPanel panel = new AdminWorkAreaJPanel(userProcessContainer, supplierDirectory, storeDirectory );
        userProcessContainer.add("AdminWAJP", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_cvsAdminBtnActionPerformed

    private void storeAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeAdminBtnActionPerformed
        LoginJPanel panel = new LoginJPanel(userProcessContainer, supplierDirectory, storeDirectory );
        userProcessContainer.add("StoreWAJP", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_storeAdminBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        SupplierLoginJPanel panel = new SupplierLoginJPanel(userProcessContainer, supplierDirectory, storeDirectory );
        userProcessContainer.add("SupplierLoginJP", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_supplierBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cvsAdminBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton storeAdminBtn;
    private javax.swing.JButton supplierBtn;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

   
}
